# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Authen-Simple
version:      1.22
version_from: Simple.pm
installdirs:  site
requires:
    CGI:                           0
    DBI:                           0
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
